import {
  Building2,
  Factory,
  GraduationCap,
  HeartPulse,
  Home,
  Plane,
  ShoppingBag,
  SunMedium,
} from "lucide-react";

export const industryPages = [
  {
    slug: "hospitals",
    title: "Digital Marketing for Hospitals",
    audience: "Hospitals, clinics, diagnostic centers, and healthcare specialists",
    icon: HeartPulse,
    promise: "Build patient trust, improve local search visibility, and generate appointment-ready enquiries.",
    challenges: ["Low Google visibility for nearby searches", "Weak patient trust signals", "Untracked enquiries from ads and calls"],
    solutions: ["Doctor and department landing pages", "Local SEO and review growth", "Google Ads for high-intent treatments", "WhatsApp appointment automation"],
    keywords: "digital marketing for hospitals in Pune, healthcare SEO, hospital Google Ads agency",
  },
  {
    slug: "manufacturers",
    title: "Digital Marketing for Manufacturers",
    audience: "Industrial manufacturers, exporters, machinery companies, and B2B suppliers",
    icon: Factory,
    promise: "Turn technical capabilities into credible B2B enquiries from buyers, dealers, and procurement teams.",
    challenges: ["Brochure-style websites with poor lead capture", "Low ranking for product and capability terms", "No nurturing flow for dealer or bulk enquiries"],
    solutions: ["Product-led website architecture", "B2B SEO and Google Search campaigns", "LinkedIn and remarketing funnels", "CRM-ready enquiry routing"],
    keywords: "digital marketing for manufacturers Pune, B2B SEO agency, industrial website development",
  },
  {
    slug: "solar-companies",
    title: "Digital Marketing for Solar Companies",
    audience: "Solar EPC companies, rooftop solar providers, and renewable energy brands",
    icon: SunMedium,
    promise: "Generate qualified residential, commercial, and industrial solar enquiries with measurable ROI.",
    challenges: ["High competition on Google", "Weak education content for buyers", "Unqualified leads from broad campaigns"],
    solutions: ["Solar landing pages by segment", "SEO for rooftop and commercial solar terms", "Google Ads with location targeting", "Lead qualification automation"],
    keywords: "digital marketing for solar companies Pune, solar SEO, solar lead generation agency",
  },
  {
    slug: "schools",
    title: "Digital Marketing for Schools",
    audience: "Schools, preschools, coaching classes, and education institutes",
    icon: GraduationCap,
    promise: "Increase admissions enquiries with trust-building content, local visibility, and parent-focused campaigns.",
    challenges: ["Seasonal admission pressure", "Outdated websites and unclear programmes", "Poor parent remarketing"],
    solutions: ["Admission landing pages", "Local SEO for area-wise searches", "Meta and Google campaigns", "Lead follow-up automation"],
    keywords: "digital marketing for schools Pune, school admission marketing, education SEO agency",
  },
  {
    slug: "real-estate",
    title: "Digital Marketing for Real Estate",
    audience: "Builders, channel partners, real estate consultants, and property projects",
    icon: Home,
    promise: "Create high-converting project journeys that turn location interest into site visits and booked calls.",
    challenges: ["High ad spend wastage", "Low-quality property leads", "Slow follow-up after form submissions"],
    solutions: ["Project landing pages", "Google and Meta lead campaigns", "Creative testing", "CRM and WhatsApp lead routing"],
    keywords: "real estate digital marketing Pune, property lead generation, real estate Google Ads agency",
  },
  {
    slug: "travel-agencies",
    title: "Digital Marketing for Travel Agencies",
    audience: "Tour operators, holiday planners, visa consultants, and travel agencies",
    icon: Plane,
    promise: "Package travel offers into search-friendly, social-ready campaigns that generate itinerary enquiries.",
    challenges: ["Low package visibility", "Price comparison pressure", "No retargeting for interested travellers"],
    solutions: ["Destination landing pages", "SEO for packages and itineraries", "Social media creatives", "WhatsApp enquiry automation"],
    keywords: "digital marketing for travel agencies Pune, travel SEO, tour package lead generation",
  },
];

export const puneLandingPages = [
  {
    slug: "website-development-company-pune",
    title: "Website Development Company Pune",
    service: "Website Development",
    icon: Building2,
    promise: "Fast, conversion-focused websites for Pune businesses that need credibility and qualified leads.",
    deliverables: ["Business website design", "Landing pages", "React and WordPress development", "SEO-ready structure"],
  },
  {
    slug: "seo-company-pune",
    title: "SEO Company Pune",
    service: "SEO",
    icon: ShoppingBag,
    promise: "Technical, local, and content SEO programmes built to improve rankings, traffic, and enquiries.",
    deliverables: ["Technical SEO audit", "Local SEO", "Content planning", "Monthly rank and traffic reporting"],
  },
  {
    slug: "google-ads-agency-pune",
    title: "Google Ads Agency Pune",
    service: "Google Ads",
    icon: Building2,
    promise: "Search, display, YouTube, shopping, and performance campaigns managed for lead quality and ROI.",
    deliverables: ["Keyword strategy", "Landing page recommendations", "Conversion tracking", "Weekly optimisation"],
  },
  {
    slug: "social-media-marketing-pune",
    title: "Social Media Marketing Pune",
    service: "Social Media Marketing",
    icon: ShoppingBag,
    promise: "Content, creatives, reels, and paid campaigns that build visibility and turn attention into action.",
    deliverables: ["Content calendar", "Creative design", "Meta campaigns", "Monthly performance reports"],
  },
  {
    slug: "shopify-development-pune",
    title: "Shopify Development Pune",
    service: "Shopify Development",
    icon: ShoppingBag,
    promise: "Shopify storefronts designed for smooth browsing, trusted checkout, and repeat sales.",
    deliverables: ["Theme setup", "Product architecture", "Payment and shipping setup", "Conversion optimisation"],
  },
  {
    slug: "ecommerce-development-pune",
    title: "Ecommerce Development Pune",
    service: "Ecommerce Development",
    icon: ShoppingBag,
    promise: "Scalable ecommerce websites with clear product journeys, secure checkout, and marketing integrations.",
    deliverables: ["Catalog planning", "Store development", "Analytics setup", "SEO and ads readiness"],
  },
];
