create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  department text not null,
  job_type text not null check (job_type in ('Full-time', 'Part-time', 'Internship', 'Freelance')),
  work_mode text not null check (work_mode in ('Work from Office', 'Remote', 'Hybrid')),
  location text not null,
  experience text not null,
  salary_range text,
  short_description text not null,
  full_description text not null,
  responsibilities text not null,
  skills text not null,
  qualification text not null,
  open_positions integer not null default 1,
  application_deadline date,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (title, department)
);

create table if not exists public.job_applications (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  full_name text not null,
  email text not null,
  phone text not null,
  experience text not null,
  current_location text not null,
  resume_file text not null,
  portfolio_link text,
  message text not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_jobs_updated_at on public.jobs;
create trigger set_jobs_updated_at
before update on public.jobs
for each row
execute function public.set_updated_at();

insert into storage.buckets (id, name, public)
values ('job-resumes', 'job-resumes', true)
on conflict (id) do update set public = true;

alter table public.jobs enable row level security;
alter table public.job_applications enable row level security;

drop policy if exists "Public can read active jobs" on public.jobs;
create policy "Public can read active jobs"
on public.jobs for select
using (status = 'active' or auth.role() = 'authenticated');

drop policy if exists "Authenticated admins can manage jobs" on public.jobs;
create policy "Authenticated admins can manage jobs"
on public.jobs for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "Public can submit job applications" on public.job_applications;
create policy "Public can submit job applications"
on public.job_applications for insert
with check (true);

drop policy if exists "Authenticated admins can read applications" on public.job_applications;
create policy "Authenticated admins can read applications"
on public.job_applications for select
using (auth.role() = 'authenticated');

drop policy if exists "Public can upload resumes" on storage.objects;
create policy "Public can upload resumes"
on storage.objects for insert
with check (bucket_id = 'job-resumes');

drop policy if exists "Public can read resumes" on storage.objects;
create policy "Public can read resumes"
on storage.objects for select
using (bucket_id = 'job-resumes');

insert into public.jobs
  (title, department, job_type, work_mode, location, experience, salary_range, short_description, full_description, responsibilities, skills, qualification, open_positions, application_deadline, status)
values
  (
    'Graphics Designer',
    'Creative',
    'Full-time',
    'Work from Office',
    'Loni Kalbhor, Pune',
    '1-3 years',
    null,
    'Create premium social media creatives, ad graphics, brand assets, and campaign visuals for digital-first clients.',
    'Praavi Consultants is looking for a creative Graphics Designer who can turn brand ideas into polished visual assets for social media, performance campaigns, websites, and client presentations.',
    'Design social media creatives and campaign assets; create brand-consistent layouts; collaborate with marketing and content teams; prepare files for web and print; maintain quality across multiple client accounts.',
    'Adobe Photoshop, Illustrator, Canva, Figma, social media creatives, layout design, typography, branding',
    'Graduate or diploma in design, fine arts, visual communication, or equivalent practical portfolio.',
    2,
    null,
    'active'
  ),
  (
    'Video Editor',
    'Creative',
    'Full-time',
    'Work from Office',
    'Loni Kalbhor, Pune',
    '1-3 years',
    null,
    'Edit reels, ads, promotional videos, and short-form content that supports high-performing digital campaigns.',
    'We are hiring a Video Editor with strong timing, storytelling, and social-first editing instincts for reels, ads, client videos, and campaign content.',
    'Edit short-form and promotional videos; add motion graphics, captions, transitions, and sound; optimize videos for Instagram, YouTube, and ads; coordinate with content and design teams.',
    'Adobe Premiere Pro, After Effects, CapCut, motion graphics, reels editing, color correction, sound design',
    'Relevant media, animation, or editing qualification preferred. Strong showreel or portfolio is required.',
    1,
    null,
    'active'
  ),
  (
    'Sales Executive',
    'Business Development',
    'Full-time',
    'Hybrid',
    'Pune',
    '0-2 years',
    null,
    'Connect with potential clients, understand their business needs, and support digital marketing sales growth.',
    'Praavi Consultants is looking for a confident Sales Executive to identify leads, communicate service value, and help businesses choose the right digital marketing solutions.',
    'Generate and follow up on leads; explain services to prospects; schedule meetings; maintain CRM updates; coordinate proposals with internal teams; support monthly sales targets.',
    'Lead generation, client communication, negotiation, CRM, digital marketing basics, presentation skills',
    'Graduate in any discipline. MBA or sales/marketing background is a plus.',
    3,
    null,
    'active'
  )
on conflict (title, department) do update set
  job_type = excluded.job_type,
  work_mode = excluded.work_mode,
  location = excluded.location,
  experience = excluded.experience,
  short_description = excluded.short_description,
  full_description = excluded.full_description,
  responsibilities = excluded.responsibilities,
  skills = excluded.skills,
  qualification = excluded.qualification,
  open_positions = excluded.open_positions,
  status = excluded.status;
